# trending hashtags for images

hastagas : (https://www.instagram.com/explore/tags/sandbar/)
    
HASHTAG GENERATOR : (https://inflact.com/tools/instagram-hashtag-generator/)

In [5]:
import numpy as np
import pandas as pd
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing import image

# Load the pre-trained ResNet50 model
model = ResNet50(weights='imagenet')

# Define a function to predict the top K imagenet labels for an input image
def predict_labels(image_path, K=10):
    # Load and preprocess the image
    img = image.load_img(image_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)

    # Use the ResNet50 model to predict the image's class probabilities
    preds = model.predict(x)
    print(preds.shape)
   # print(preds)

    # Decode the predictions into a list of imagenet labels and their probabilities
    imagenet_labels = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt", header=None)[0]
    top_preds = np.argsort(-preds, axis=1)[0][:K] # # Axis along which to sort
    print('top 10 indexes are',top_preds)
    print()
    labels = [imagenet_labels[idx] for idx in top_preds]
    probs = [preds[0][idx] for idx in top_preds]
    return labels, probs

    
# Define a function to generate hashtags for an input image
def generate_hashtags(image_path, K=10):
    # Use the predict_labels function to get the top imagenet labels for the image
    labels, probs = predict_labels(image_path, K)

    # Convert the imagenet labels to hashtags and return the top K hashtags
    hashtags = [f"#{label.replace(' ','').replace('-','')}" for label in labels]
    return hashtags[:K], probs



In [11]:
hashtags = generate_hashtags("C:/Users/pramod/Desktop/ANN/TASK/image1.png", K=10)
print(hashtags)

1/1 [==============================] - 0s 120ms/step
(1, 1000)
top 10 indexes are [792 463 796 855 447 968 514 470 541 899]

(['#shoppingcart', '#broom', '#ski', '#theatercurtain', '#binder', '#espresso', '#cornet', '#caldron', '#drillingplatform', '#waterbottle'], [0.17709234, 0.13532585, 0.11372058, 0.04842068, 0.039625384, 0.027808161, 0.01604844, 0.015046145, 0.013765015, 0.013372133])


In [12]:
imagenet_labels[792], imagenet_labels[463]

('shopping cart', 'broom')

In [10]:
imagenet_labels[459]

'brass'

In [8]:
imagenet_labels = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt", header=None)[0]
print(imagenet_labels.shape)
imagenet_labels.head(10)


(1001,)


0           background
1                tench
2             goldfish
3    great white shark
4          tiger shark
5           hammerhead
6         electric ray
7             stingray
8                 cock
9                  hen
Name: 0, dtype: object

In [15]:
imagenet_labels[990:]

990                  hip
991              buckeye
992         coral fungus
993               agaric
994            gyromitra
995            stinkhorn
996            earthstar
997     hen-of-the-woods
998               bolete
999                  ear
1000       toilet tissue
Name: 0, dtype: object

In [27]:
sum([0.17709234, 0.13532585, 0.11372058, 0.04842068, 0.039625384, 0.027808161, 0.01604844, 0.015046145, 0.013765015, 0.013372133])

0.6002247280000002

In [ ]:
#influencermarketinghub

In [13]:
import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image

from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing import image

# Load the pre-trained ResNet50 model
model = ResNet50(weights='imagenet')

# Define a function to predict the top K imagenet labels for an input image
def predict_labels(image_path, K=10):
    # Load and preprocess the image
    img = image.load_img(image_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)

    # Use the ResNet50 model to predict the image's class probabilities
    preds = model.predict(x)

    # Decode the predictions into a list of imagenet labels and their probabilities
    imagenet_labels = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt", header=None)[0]
    top_preds = np.argsort(-preds, axis=1)[0][:K] # Axis along which to sort
    labels = [imagenet_labels[idx] for idx in top_preds]
    probs = [preds[0][idx] for idx in top_preds]
    return labels, probs

# Define a function to generate hashtags for an input image
def generate_hashtags(image_path, K=10):
    # Use the predict_labels function to get the top imagenet labels for the image
    labels, _ = predict_labels(image_path, K)

    # Convert the imagenet labels to hashtags and return the top K hashtags
    hashtags = [f"#{label.replace(' ', '')}" for label in labels]
    return hashtags[:K]

# Define the Streamlit app layout and functionality 
def app():
    st.title("Image Hashtag Generator")

    #target_size = (160, 160)
    # Upload the image file
    uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

    # If an image is uploaded, generate hashtags for it
    if uploaded_file is not None:
        # Display the uploaded image
        image = Image.open(uploaded_file)
        #image = image.resize(target_size)
        st.image(image, caption="Uploaded image", use_column_width=True)

        # Generate hashtags for the image
        image_path = "uploaded_image.jpg"
        with open(image_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
        hashtags = generate_hashtags(image_path, K=10)

        # Display the hashtags
        st.subheader("Generated Hashtags")
        for hashtag in hashtags:
            st.write(hashtag)

# Run the Streamlit app
if __name__ == "__main__":
    app()


2023-04-19 19:11:49.275 
  command:

    streamlit run C:\Users\pramod\AppData\Roaming\Python\Python310\site-packages\ipykernel_launcher.py [ARGUMENTS]


In [77]:

x = np.array([[0, 3,14,5], [2, 10,5,6]])
print(x)

print()
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
print(ind)
print()
ind = np.argsort(x, axis=1)  # sorts along first axis (down)
print(ind)

[[ 0  3 14  5]
 [ 2 10  5  6]]

[[0 0 1 0]
 [1 1 0 1]]

[[0 1 3 2]
 [0 2 3 1]]


In [81]:

x = np.array([[0, 3,14,5,2,3,4,5,6,7,8], [2, 10,5,6,4,5,6,7,8,7,8]])
print(x[0])
print(x[0].shape)
print()
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
print(ind)
print()
ind = np.argsort(x, axis=1)  # sorts along first axis (down)
print(ind)

[ 0  3 14  5  2  3  4  5  6  7  8]
(11,)

[[0 0 1 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 1 1 1]]

[[ 0  4  1  5  6  3  7  8  9 10  2]
 [ 0  4  2  5  3  6  7  9  8 10  1]]


In [103]:
x = np.array([[0, 3,14,5,2,3,4,5,6,7,8]])
print(x[:5])
print(x[0].shape)
print()
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
print(ind)
print()
ind = np.argsort(x, axis=1)  # sorts along first axis (down)
print(ind)

[[ 0  3 14  5  2  3  4  5  6  7  8]]
(11,)

[[0 0 0 0 0 0 0 0 0 0 0]]

[[ 0  4  1  5  6  3  7  8  9 10  2]]


In [104]:
x = np.array([[0, 3,14,5,2,3,4,5,6,7,8], [0, 3,14,5,2,3,4,5,6,7,8]])
print(x[:5])

[[ 0  3 14  5  2  3  4  5  6  7  8]
 [ 0  3 14  5  2  3  4  5  6  7  8]]


In [108]:
x = np.array([[0, 3,14,5,2,3,4,5,6,7,8]])
print(x[0][:5])

[ 0  3 14  5  2]
